{% set version = "3.9.1" %}

package:
  name: nltk
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/n/nltk/nltk-{{ version }}.tar.gz
  sha256: 87d127bd3de4bd89a4f81265e5fa59cb1b199b27440175370f7417d2bc7ae868

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - nltk = nltk.cli:cli

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - click
    - joblib
    - regex >=2021.8.3
    - tqdm

test:
  imports:
    - nltk
    - nltk.app
    - nltk.ccg
    - nltk.chat
    - nltk.chunk
    - nltk.classify
    - nltk.cluster
    - nltk.corpus
    - nltk.corpus.reader
    - nltk.draw
    - nltk.inference
    - nltk.lm
    - nltk.metrics
    - nltk.misc
    - nltk.parse
    - nltk.sem
    - nltk.sentiment
    - nltk.stem
    - nltk.tag
    - nltk.tbl
    - nltk.test
    - nltk.test.unit
    - nltk.test.unit.translate
    - nltk.tokenize
    - nltk.translate
    - nltk.twitter
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - nltk --help

about:
  home: http://nltk.org/
  license_file: LICENSE.txt
  license: Apache-2.0
  license_family: Apache
  summary: Natural Language Toolkit
  dev_url: https://github.com/nltk/nltk
  doc_url: http://www.nltk.org/

extra:
  recipe-maintainers:
    - jan-janssen
    - quartox
    - synapticarbors
