schema_version: 1

context:
  version: 3.9.2

package:
  name: nltk
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/n/nltk/nltk-${{ version }}.tar.gz
  sha256: 0f409e9b069ca4177c1903c3e843eef90c7e92992fa4931ae607da6de49e1419

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  python:
    entry_points:
      - nltk = nltk.cli:cli

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - click
    - joblib
    - regex >=2021.8.3
    - tqdm

tests:
  - python:
      imports:
        - nltk
        - nltk.app
        - nltk.ccg
        - nltk.chat
        - nltk.chunk
        - nltk.classify
        - nltk.cluster
        - nltk.corpus
        - nltk.corpus.reader
        - nltk.draw
        - nltk.inference
        - nltk.lm
        - nltk.metrics
        - nltk.misc
        - nltk.parse
        - nltk.sem
        - nltk.sentiment
        - nltk.stem
        - nltk.tag
        - nltk.tbl
        - nltk.test
        - nltk.test.unit
        - nltk.test.unit.translate
        - nltk.tokenize
        - nltk.translate
        - nltk.twitter
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - nltk --help

about:
  license_file: LICENSE.txt
  license: Apache-2.0
  summary: Natural Language Toolkit
  homepage: http://nltk.org/
  repository: https://github.com/nltk/nltk
  documentation: http://www.nltk.org/

extra:
  recipe-maintainers:
    - jan-janssen
    - quartox
    - synapticarbors
